### ISSUE TITLE
not enough arguments for format string

### ISSUE THREAD

**Issue by cghanke** [jupyterlab/jupyterlab_collaboration#92]
In the debug-statement 
https://github.com/jupyterlab/jupyterlab_collaboration/blob/8d7cd9007bf687f48c0c1f671dcbf00dc6137890/jupyter_collaboration/handlers.py#L161
the parameter "file_id" is apparently missing.

**Comment by hbcarlos** [comment]
Hey @cghanke! Thanks for opening an issue.
You are right. The `file_id` is missing. Do you want to open a PR to fix it?
